# Generated by Django 3.2.13 on 2022-06-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='homeadress',
            field=models.CharField(max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
