# Generated by Django 3.2.13 on 2022-06-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0002_auto_20220606_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='homeadress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='phone',
            new_name='fone',
        ),
    ]
