# Generated by Django 3.2.13 on 2022-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0003_auto_20220606_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='conta_contrato',
            field=models.CharField(max_length=20, null=True, verbose_name='Conta Contrato: '),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='decimal_x',
            field=models.CharField(max_length=15, null=True, verbose_name='Decimal - X:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='decimal_y',
            field=models.CharField(max_length=15, null=True, verbose_name='Decimal - Y:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=20, null=True, verbose_name='Email: '),
        ),
        migrations.AddField(
            model_name='cliente',
            name='geografica',
            field=models.CharField(max_length=15, null=True, verbose_name='Geografica:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ger_mensal',
            field=models.CharField(max_length=8, null=True, verbose_name='Geração Mensal:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inversor',
            field=models.CharField(max_length=20, null=True, verbose_name='Inversor Utilizado:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='link_endereco',
            field=models.CharField(max_length=30, null=True, verbose_name='Link Localização: '),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mod',
            field=models.CharField(max_length=20, null=True, verbose_name='Modulos Utilizados:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mudar_padrao',
            field=models.BooleanField(null=True, verbose_name='Padrao precisa ser mudado ?:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qt_inv',
            field=models.IntegerField(null=True, verbose_name='Quantidade de inversores:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qt_mod',
            field=models.IntegerField(null=True, verbose_name='Quantidade de modulos:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sis_pot',
            field=models.CharField(max_length=4, null=True, verbose_name='Potencia do Sistema:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_geracao',
            field=models.CharField(max_length=20, null=True, verbose_name='Tipo de geração:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_padrao',
            field=models.CharField(max_length=10, null=True, verbose_name='Padrao de entrada:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='utm_x',
            field=models.CharField(max_length=15, null=True, verbose_name='UTM - X:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='utm_y',
            field=models.CharField(max_length=15, null=True, verbose_name='UTM - Y:'),
        ),
    ]
