# Generated by Django 4.0.5 on 2022-06-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0006_cliente_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='disj',
            field=models.CharField(choices=[('25A-MONO', '25A - MONO'), ('40A-MONO', '40A - MONO'), ('63A-MONO', '63A - MONO'), ('40A-TRI', '40A - TRI'), ('63A-TRI', '63A - TRI'), ('80A-TRI', '80A - TRI'), ('100A-TRI', '100A - TRI'), ('125A-TRI', '125A - TRI')], max_length=15, null=True, verbose_name='Disjuntor de entrada do sistema'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='strBx',
            field=models.CharField(max_length=200, null=True, verbose_name='Modelo de StringBox usada'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inversor',
            field=models.CharField(max_length=20, null=True, verbose_name='Inversor(es) Utilizado(s):'),
        ),
    ]
