# Generated by Django 4.0.5 on 2022-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0007_cliente_disj_cliente_strbx_alter_cliente_inversor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='disjSis',
            field=models.CharField(max_length=20, null=True, verbose_name='Disjuntor de proteção CA do sistema:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dps',
            field=models.CharField(max_length=20, null=True, verbose_name='DPS CC do Sistema:'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='obs',
            field=models.CharField(max_length=500, null=True, verbose_name='Observações: '),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pagamento',
            field=models.CharField(max_length=30, null=True, verbose_name='Forma de pagamento:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='disj',
            field=models.CharField(choices=[('25A-MONO', '25A - MONO'), ('40A-MONO', '40A - MONO'), ('63A-MONO', '63A - MONO'), ('40A-TRI', '40A - TRI'), ('63A-TRI', '63A - TRI'), ('80A-TRI', '80A - TRI'), ('100A-TRI', '100A - TRI'), ('125A-TRI', '125A - TRI')], max_length=15, null=True, verbose_name='Disjuntor de entrada do sistema:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='strBx',
            field=models.CharField(max_length=200, null=True, verbose_name='Modelo de StringBox usada:'),
        ),
    ]
