# Generated by Django 4.0.5 on 2022-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0010_cliente_equipe_cliente_fim_cliente_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fim',
        ),
        migrations.AddField(
            model_name='cliente',
            name='inicio_2',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da obra'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio da obra'),
        ),
    ]
