# Generated by Django 4.0.5 on 2022-06-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0011_remove_cliente_fim_cliente_inicio_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='inicio_2',
        ),
    ]
