# Generated by Django 3.2.13 on 2022-07-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0012_remove_cliente_inicio_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da obra'),
        ),
    ]
