# Generated by Django 3.2.13 on 2022-07-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0013_cliente_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='equipe',
            field=models.CharField(max_length=300, null=True, verbose_name='Equipe de instalação: '),
        ),
    ]
