# Generated by Django 3.2.13 on 2022-07-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0014_alter_cliente_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='disj',
            field=models.CharField(choices=[('25A-MONO', '25A - MONO'), ('40A-MONO', '40A - MONO'), ('63A-MONO', '63A - MONO'), ('40A-TRI', '40A - TRI'), ('63A-TRI', '63A - TRI'), ('80A-TRI', '80A - TRI'), ('100A-TRI', '100A - TRI'), ('125A-TRI', '125A - TRI')], max_length=15, null=True, verbose_name='Disjuntor de entrada do sistema:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Email: '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fone',
            field=models.CharField(max_length=25, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_geracao',
            field=models.CharField(choices=[('individual', 'individual'), ('autoconsumo', 'autoconsumo remoto')], max_length=20, null=True, verbose_name='Tipo de geração:'),
        ),
    ]
